#!/usr/bin/env node
import { execFileSync, spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { EOL } from "node:os";

const envPath = new URL("../.env", import.meta.url);
const examplePath = new URL("../.env.example", import.meta.url);

const requiredCommands = ["node", "npm", "docker"];

main();

async function main() {
  console.log("Armorer Gauntlet setup");
  console.log("======================");

  for (const command of requiredCommands) {
    requireCommand(command);
  }
  requireNodeMajor(20);

  const hasColima = hasCommand("colima");
  const dockerReady = dockerInfoWorks();
  if (!dockerReady) {
    if (!hasColima) {
      fail("Docker is not running and Colima was not found. Install Colima or start Docker Desktop, then rerun make setup.");
    }
    run("colima", ["start"], "Starting Colima");
  } else if (!hasColima) {
    warn("Colima was not found, but Docker is running. Continuing with the active Docker engine.");
  }

  run("docker", ["compose", "version"], "Checking Docker Compose");

  if (hasCommand("codex")) {
    run("codex", ["--version"], "Checking Codex CLI");
  } else {
    warn("codex was not found. Install and log in to Codex before running make daemon.");
  }

  run("npm", ["install"], "Installing npm dependencies");
  run("npm", ["run", "build:libs"], "Building workspace libraries");

  const env = readEnvFile();
  const merged = {
    PWA_PORT: "3000",
    RELAY_PORT: "8787",
    FRONT_DOOR_PORT: "8080",
    RELAY_URL: "ws://127.0.0.1:8787",
    VAPID_SUBJECT: "mailto:you@example.com",
    ...env
  };
  const vapid = await ensureVapid(merged);
  if (!merged.VAPID_PUBLIC_KEY) merged.VAPID_PUBLIC_KEY = vapid.publicKey;
  if (!merged.VAPID_PRIVATE_KEY) merged.VAPID_PRIVATE_KEY = vapid.privateKey;
  if (!merged.PUBLIC_VAPID_PUBLIC_KEY && merged.VAPID_PUBLIC_KEY) {
    merged.PUBLIC_VAPID_PUBLIC_KEY = merged.VAPID_PUBLIC_KEY;
  }
  writeEnvFile(merged);

  console.log("");
  console.log("Ready.");
  console.log("  make start    # start everything and print the phone QR");
}

function requireCommand(command) {
  if (!hasCommand(command)) fail(`${command} is required but was not found in PATH.`);
}

function requireNodeMajor(minimumMajor) {
  const major = Number(process.versions.node.split(".")[0]);
  if (!Number.isFinite(major) || major < minimumMajor) {
    fail(`Node.js ${minimumMajor}+ is required; found ${process.versions.node}.`);
  }
}

function hasCommand(command) {
  const result = spawnSync(command, ["--version"], { stdio: "ignore" });
  return result.status === 0 || result.status === 1;
}

function dockerInfoWorks() {
  const result = spawnSync("docker", ["info"], { stdio: "ignore" });
  return result.status === 0;
}

function run(command, args, label) {
  console.log(`${label}...`);
  try {
    execFileSync(command, args, { stdio: "inherit" });
  } catch {
    fail(`${label} failed.`);
  }
}

function readEnvFile() {
  return parseEnvText(readFileSafe(envPath) ?? readFileSafe(examplePath) ?? "");
}

function readFileSafe(path) {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return undefined;
  }
}

function parseEnvText(text) {
  const values = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const equals = trimmed.indexOf("=");
    if (equals === -1) continue;
    values[trimmed.slice(0, equals)] = trimmed.slice(equals + 1);
  }
  return values;
}

async function ensureVapid(env) {
  if (env.VAPID_PUBLIC_KEY && env.VAPID_PRIVATE_KEY) {
    return {
      publicKey: env.VAPID_PUBLIC_KEY,
      privateKey: env.VAPID_PRIVATE_KEY
    };
  }

  const webPush = await import("web-push");
  return webPush.default.generateVAPIDKeys();
}

function writeEnvFile(values) {
  const order = [
    "PWA_PORT",
    "RELAY_PORT",
    "FRONT_DOOR_PORT",
    "RELAY_URL",
    "VAPID_SUBJECT",
    "VAPID_PUBLIC_KEY",
    "VAPID_PRIVATE_KEY",
    "PUBLIC_VAPID_PUBLIC_KEY"
  ];
  const known = new Set(order);
  const existing = parseEnvText(readFileSafe(envPath) ?? "");
  const extraLines = Object.entries(existing)
    .filter(([key]) => !known.has(key))
    .map(([key, value]) => `${key}=${value}`);
  const lines = [
    "# Generated by make setup. Edit values here; setup will not overwrite them.",
    ...order.map((key) => `${key}=${values[key] ?? ""}`)
  ];
  if (extraLines.length) {
    lines.push("", "# Preserved custom values", ...extraLines);
  }
  writeFileSync(envPath, `${lines.join(EOL)}${EOL}`);
}

function warn(message) {
  console.warn(`Warning: ${message}`);
}

function fail(message) {
  console.error(`Error: ${message}`);
  process.exit(1);
}
